# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('article_type', models.TextField(blank=True, null=True)),
                ('no_pages', models.IntegerField(blank=True, null=True)),
                ('document_link', models.TextField(blank=True, null=True)),
                ('fetched_on', models.TextField(blank=True, null=True)),
                ('document_text', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('enhanced_on', models.TextField(blank=True, null=True)),
                ('abstracts', models.TextField(blank=True, null=True)),
                ('article_rank', models.IntegerField(blank=True, null=True)),
                ('number_of_mentions', models.IntegerField(blank=True, null=True)),
                ('normalized_number_of_mentions', models.FloatField(blank=True, db_column='NORMALIZED_number_of_mentions', null=True)),
                ('date_of_analysis', models.TextField(blank=True, null=True)),
                ('used_search_terms', models.TextField(blank=True, null=True)),
                ('estimated_publication_date', models.IntegerField(blank=True, null=True)),
                ('row_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_data',
                'managed': True,
            },
        ),
    ]
