# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddata',
            name='id',
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='row_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
